kind = "mobile"
previewPath = "/bloomy-mobile/"
title = "Bloomy Mobile"
version = "1.0.0"
id = "artifacts/bloomy-mobile"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/bloomy-mobile/" ]
localPort = 21239

[services.development]
run = "pnpm --filter @workspace/bloomy-mobile run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/bloomy-mobile", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/bloomy-mobile", "run", "serve" ]

[services.env]
PORT = "21239"
BASE_PATH = "/bloomy-mobile/"
